n = int(input('Informe um número: '))
print('A taboada de {} é:'.format(n))
print('='*20)
print('{:2} x {:2} = {:3}'.format(1, n, n * 1))
print('{:2} x {:2} = {:3}'.format(2, n, n * 2))
print('{:2} x {:2} = {:3}'.format(3, n, n * 3))
print('{:2} x {:2} = {:3}'.format(4, n, n * 4))
print('{:2} x {:2} = {:3}'.format(5, n, n * 5))
print('{:2} x {:2} = {:3}'.format(6, n, n * 6))
print('{:2} x {:2} = {:3}'.format(7, n, n * 7))
print('{:2} x {:2} = {:3}'.format(8, n, n * 8))
print('{:2} x {:2} = {:3}'.format(9, n, n * 9))
print('{:2} x {:2} = {:3}'.format(10,n, n * 10))
